
const swaggerAutogen = require('swagger-autogen')()

const doc = {
    info: {
        version: "1.0.0",
        title: "TodoListApp",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3002",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        },
        {
            "name": "Project",
            "description": "Access to project by User"
        },
        {
            "name": "Task",
            "description": "Access to Task"
        },
        {
            "name": "Dashboard",
            "description": "Access to dashboard"
        }
    ],
    securityDefinitions: {
        api_key: {
            type: "apiKey",
            name: "api_key",
            in: "header"
        },
        petstore_auth: {
            type: "oauth2",
            authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
            flow: "implicit",
            scopes: {
                read_pets: "read your pets",
                write_pets: "modify pets in your account"
            }
        }
    },
    'definitions': {
        User: {
            email: "hai@gmail.com",
            password: "hai",
            firstName: "Hai",
            lastName: "Nguyen",
            projects: [{
                $ref: '#/definitions/Project'
            }],
        },
        Project: {
            title: "write API",
            ownerId: "1",
            users: [{
                $ref: '#/definitions/User'
            }]
        },
        listUser: {
            email: ['hai@gmail.com', 'abc@gmail.com']
        }
    },
    components: {
        createTask: {
            type: 'object',
            properties: {
                taskName: {
                    type: 'string',
                    example: "Tạo task 1"
                },
                description: {
                    type: 'string',
                    example: "viet nhieu api"
                },
                deadline: {
                    type: 'string',
                    example: "2023-07-29 16:00:46"
                },
                email: {
                    type: 'array',
                    example: ['hai@gmail.com', 'abc@gmail.com']
                }
            }
        }
    }
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./src/routes/*.ts']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./src/index.ts')           // Your project's root file
})